### ISSUE TITLE
kshootmania 1.61 blocks these songs

### ISSUE THREAD

**Issue by nieknooijens** [Schinizer/kshootmaniasdvx#12]
as the title says, kshootmania 1.61 actually blocks any konami content because of lawsuits (konami is a bitch) so stay with the old version or switch to this:
https://github.com/guusw/unnamed-sdvx-clone
if you want to continue playing sdvx charts outside of japan.

**Comment by Uwy** [comment]
Didn't updated my kshoot but I've a few questions about this :
- Is the 1.61 update mandatory ?
- Any clue on how it blocks this content ? 
  - Do it checks the name / description ?
  - Do it checks the audio content in itself (like youtube copyright bot) ?
  - Do the copyright database is hardcoded or accessed online ?

Reason why I asks this is that while the clone is still in dev, workarounds can be found easily until it becomes stable (full controller support and so on).

**Comment by nieknooijens** [comment]
the 1.61 update is not mandatory, but the official site does only serve the 1.61 update.
I was able to get 1.50 back (without the DRM) by using the internet archive, it appears that those old mega links are still up:
https://mega.nz/#!hl5H1YKS!vzOiNoKQuLh3z6RAvijAK2EkVGFxN5ZgInUdnM2VfYU
I have no idea how it blocks it, I tried changing stuff but the error at startup kept appearing until I removed the sdvx song entirely from the songs folder.

**Comment by Uwy** [comment]
If anyone can't find download link for 1.50, here's one : https://cloud.uwy.moe/s/bOxKQrGTdiiBOdY

**Comment by Schinizer** [comment]
It just checks for the fix formatting that the song pack is following.

**Comment by nieknooijens** [comment]
cant we make a randomizer script in python or so?
one that randomizes the filenames and puts 4 random chars behind the song title/artist and then adds a single but random sample to the .ogg file to mismatch the checksums every time?

anyhow the "unnamed-sdvx-clone" is making quite some progress, score screen has been implemented and there is HID support now.

**Comment by itemx** [comment]
afaik ks 164d removes the limit? at least it works on mine now.

**Comment by Uwy** [comment]
@itemx Yes it does
I think this issue can be closed.

**Comment by nieknooijens** [comment]
Yep it's fixed
